web-app-chart:
  image: "sebokoslav/ci-cd-test-app:1.0.17+17"
  appName: "cicdtest"
  environment: "prod"
  repo: "https://github.com/sebokoslav/ci-cd-test-app-config.git"
  containerPort: 80
  externalPort: 3001
  targetPort: 80
  replicas: 2